eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

  client:
    service-url:
      registry-fetch-interval-seconds: 5
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
